---
driver:
  name: vagrant
  customize:
    memory: 4096
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 8888, host: 8888}]
  - ["forwarded_port", {guest: 8088, host: 8088}]

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.3

platforms:
  - name: ubuntu-14.04
    run_list:
     - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[hadoop::install]
      - recipe[flink::install]
      - recipe[hadoop::nn]
      - recipe[hadoop::dn]
      - recipe[hadoop::rm]
      - recipe[hadoop::nm]
      - recipe[flink::jobmanager]
      - recipe[flink::jobmanager-hadoop]
      - recipe[flink::taskmanager]
      - recipe[flink::wordcount]
    attributes:
         java:
           jdk_version: 8
           install_flavor: oracle
         vagrant: "true"
         hadoop:
            nn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
         flink:
            jobmanager:
               public_ips: ["10.0.2.15"]
               private_ips: ["10.0.2.15"]
            taskmanager:
               public_ips: ["10.0.2.15"]
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
