---
driver:
  name: vagrant
  customize:
    memory: 4096
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.3

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[hadoop::install]
      - recipe[flink::install]
      - recipe[hadoop::nn]
      - recipe[hadoop::dn]
      - recipe[flink::jobmanager]
      - recipe[flink::taskmanager]
    attributes:
         java:
            jdk_version: 8
         vagrant: "true"
         hadoop:
            nn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
         flink:
            jobmanager:
               public_ips: ["10.0.2.15"]
               private_ips: ["10.0.2.15"]
            taskmanager:
               public_ips: ["10.0.2.15"]
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
